[package]
name = "shs-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = { features = ["termion"], version = "0.24.0"}
crossterm = "0.27"
termion = "2.0.3"
rand = "0.8"
